### ISSUE TITLE
Aluminum wire (in BOM) not apparently used in build instructions

### ISSUE THREAD

**Issue by tom-f-oconnell** [FlySorterLLC/MAPLEHardware#1]
Could you clarify the purpose of the aluminum wire (8904K92) in the build instructions?  Searching for "wire", and reading the instruction section on the organism manipulator didn't seem to turn up any references to the wire.  If it's not needed anymore, you could also just remove it from the BOM.

**Comment by debivort** [comment]
Hi - Hopefully Dave also weighs in, but I believe the wire is there to assist in making the blunt tubes that go into the fly manipulator tip. You can insert the aluminum wire into the narrow tubes, and cut through the pair without collapsing the narrow tubes. But the particular wire diameter that's specced in the BOM would only help with the wider of the two needles.

**Comment by flysorter** [comment]
Hi Tom - that's a good catch. The aluminum wire was there as an alternate way to fashion the fly manipulator, but ultimately, the tubes-in-a-tube method worked much better. I'll remove it from the bill of materials.
