### ISSUE TITLE
Laser cut parts

### ISSUE THREAD

**Issue by tom-f-oconnell** [FlySorterLLC/MAPLEHardware#6]
Acrylic parts "end panel" and "work surface" are mentioned in the BOM, and it seems at least the "end panel" is in the master Solidworks assembly, but neither is mentioned in the build instructions, nor are they in the Drawings folder.

Would you mind exporting either a DXF or a PDF of these / all lasercuttable parts, assuming these parts are still used?  And could you also put a blurb in the instructions saying what to attach to the end panel and how?

Thanks!

**Comment by flysorter** [comment]
Drawings added, working on the instructions presently. Thanks.

**Comment by tom-f-oconnell** [comment]
The worksurface in the PDF seems to be different from the one in the eLife paper (which seems to be the same as the one depicted in the preprint).  Do you have a version with the mounting holes / cable passthroughs, etc?

It would be nice to make my modules fit a canonical mounting hole spacing, rather than just come up with my own mounting footprint arbitrarily, so that my modules could hypothetically be re-used across labs without having to change the work surface or make adapters.

**Comment by flysorter** [comment]
Honestly, there isn't a canonical grid for the worksurface at the moment. The way we made things repeatable was to mount all the modules required for an experiment to a second, thinner, clear sheet of acrylic that gets placed on the permanently-attached bed. It's up to you to figure out where you'd want pass-thrus and the like.

(It's true that there is a grid of holes in the work surface in photos in the paper, but they weren't used.)
